version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/app"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/dashboard"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
