version: 2

aliases:
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn |
    yarn
    yarn workspace @move/types run build
    yarn workspace @move/core run build

defaults: &defaults
  working_directory: ~/move
  docker:
    - image: circleci/node:12.6.0-stretch

jobs:
  checkout_environment:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: *yarn
      - save_cache: *save-yarn-cache

      - persist_to_workspace:
          root: .
          paths: .

  test_static:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/move
      - run:
          name: Run TypeScript
          command: yarn workspaces run tsc
      - run:
          name: Run ESLint
          command: yarn workspaces run lint

workflows:
  version: 2
  test:
    jobs:
      - checkout_environment
      - test_static:
          requires:
            - checkout_environment
