name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run static tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Run static tests
      run: |
        yarn workspaces run tsc
        yarn workspaces run lint
