name: Lint and Test

on: [push, pull_request]

jobs:
  test:
    name: Run static tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install dependencies
      run: yarn install

    - name: Setup generated types
      run: yarn workspace @move/core build

    - name: Run lint
      run: yarn workspaces run lint

    - name: Run typecheck
      run: yarn workspaces run tsc
